-module(ex_banking_operation_tests).

-include_lib("eunit/include/eunit.hrl").
-include("ex_banking_test.hrl").



-spec ?test_spec(test).

%% automatically generated by eunit



-spec ?test_spec(can_get_error_on_invalid_type_test).

can_get_error_on_invalid_type_test() ->
    ?assertException(error, function_clause, ex_banking_operation:new(invalid_type, 0)).



-spec ?test_spec(can_get_error_on_invalid_amount_test).

can_get_error_on_invalid_amount_test() ->
    ?assertException(error, function_clause, ex_banking_operation:new(deposit, -1)),
    ?assertException(error, function_clause, ex_banking_operation:new(withdraw, 1.11)).



-spec ?test_spec(can_get_fields_test).

can_get_fields_test() ->
    Operation = ex_banking_operation:new(deposit, 100),
    ?assertMatch(_Id when is_reference(_Id), ex_banking_operation:id(Operation)),
    ?assertMatch(deposit, ex_banking_operation:type(Operation)),
    ?assertMatch(100, ex_banking_operation:amount(Operation)).
